[package]
name = "prettier-please"
version = "0.1.16"
authors = ["David Tolnay <dtolnay@gmail.com>", "Jon Kelley"]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
description = "A minimal `syn` syntax tree pretty-printer"
repository = "https://github.com/dtolnay/prettyplease"
documentation = "https://docs.rs/prettyplease"
readme = "README.md"
links = "prettyplease01"
autoexamples = false
exclude = ["cargo-expand"]

[features]
verbatim = ["syn/parsing"]

[dependencies]
proc-macro2 = { version = "1.0.63", default-features = false }
syn = { version = "2.0.23", default-features = false, features = ["full"] }

[dev-dependencies]
syn = { version = "2.0.23", default-features = false, features = ["parsing"] }

[lib]
doc-scrape-examples = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata.playground]
features = ["verbatim"]
